name: withoutnotification
version: '${version}'
main: com.github.xinboshin.withoutnotification.spigot.withoutnotification
api-version: 1.17
load: POSTWORLD
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
authors: [ Kaspian ]
description: A plugin that removed annoying unsafe server popup.
commands:
  withoutnotification:
    description: Main withoutnotification command.
    permission: withoutnotification.commands
folia-supported: true
