name: withoutnotifications
version: '${version}'
main: com.github.xinboshin.withoutnotifications.spigot.withoutnotifications
api-version: 1.17
load: POSTWORLD
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
authors: [ Kaspian ]
description: A plugin that removed annoying unsafe server popup.
commands:
  withoutnotifications:
    description: Main withoutnotifications command.
    permission: withoutnotifications.commands
folia-supported: true
