config-version: 33

# Должны ли мы собирать анонимные данные о вашем сервере?
# по умолчанию установлено значение false.
bstats: false

# Следует ли нам удалить [Not Secure] из /say?
# Есть очень маленький шанс что-нибудь подхватить.
# это не должно быть перехвачено. Если это произойдет, сообщите об этом
# инцидент с проблемами на Github из-за отсутствия уведомления.
filter-not-secure: true

# Нам не нужен этот пакет, если
# мы не подписываем сообщения.
send-header: false

# Следует ли запускать программу установки при первом запуске?
# Полезно для всех видов настроек или узлов сервера.
auto-setup: false

# Следует ли запретить сообщать о сообщениях в чате?
# Работает только для версий выше 1.19(.0).
block-chat-reports: true

# Должно ли появляться всплывающее окно для игроков?
# Не рекомендуется.
show-popup: false

# --- ТОЛЬКО для SPIGOT ---
# Перечитывайте ссылки в сообщениях, по которым можно перейти.
# Это может привести к несовместимости!
clickable-urls: false

# --- ТОЛЬКО для SPIGOT ---
# Расположение файла server.properties относительно папки сервера.
# Не меняйте, если это не требуется.
properties-location: server.properties

# Не прикасайтесь к тем, что ниже!
first-run: true
ask-bstats: true
setup-mode: true
